"""add user_id and sender to messages

Revision ID: ef52eb4f1f8f
Revises: 906eaf021d4a
Create Date: 2026-02-09 15:19:51.531864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef52eb4f1f8f'
down_revision: Union[str, None] = '906eaf021d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('sender', sa.String(), nullable=False, server_default='system'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
